version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      - db
      - neural-network  
    environment:
      - NEURAL_NETWORK_URL=http://neural-network:8001

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: report_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neural-network:  
    build: ./neural-network  
    ports:
      - "8001:8000"  
    volumes:
      - ./neural-network:/app
    environment:
      - MODEL_NAME=t5-small  

volumes:
  postgres_data:
